global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'load_balancer'
    static_configs:
      - targets: ['192.168.0.103:8000']

  - job_name: 'backends'
    static_configs:
      - targets: ['192.168.0.103:8081', '192.168.0.103:8082', '192.168.0.103:8083']
